# Generated by Django 5.0.1 on 2026-02-13 11:36

import django.db.models.deletion
from django.db import migrations, models


def create_companies_and_migrate_data(apps, schema_editor):
    """Create 5 companies and migrate existing users/devices to REDPAY company"""
    Company = apps.get_model('api', 'Company')
    DashUser = apps.get_model('api', 'DashUser')
    Device = apps.get_model('api', 'Device')
    
    # Create the 5 companies
    companies_data = [
        {'code': 'REDPAY', 'name': 'RedPay'},
        {'code': 'BROPAY', 'name': 'BroPay'},
        {'code': 'HYPAY', 'name': 'HyPay'},
        {'code': 'CSAPAY', 'name': 'CsaPay'},
        {'code': 'KYPAY', 'name': 'KyPay'},
    ]
    
    created_companies = {}
    for company_data in companies_data:
        company, created = Company.objects.get_or_create(
            code=company_data['code'],
            defaults={'name': company_data['name'], 'is_active': True}
        )
        created_companies[company_data['code']] = company
        if created:
            print(f"Created company: {company.code} - {company.name}")
    
    # Get REDPAY company for default assignments
    redpay_company = created_companies.get('REDPAY')
    if not redpay_company:
        redpay_company = Company.objects.get(code='REDPAY')
    
    # Migrate existing users to REDPAY company
    users_updated = 0
    for user in DashUser.objects.filter(company__isnull=True):
        user.company = redpay_company
        user.save(update_fields=['company'])
        users_updated += 1
    print(f"Migrated {users_updated} users to REDPAY company")
    
    # Migrate existing devices to companies
    devices_updated = 0
    for device in Device.objects.filter(company__isnull=True):
        # If device has assigned users, try to determine company from users
        assigned_users = device.assigned_to.all()
        if assigned_users.exists():
            # Get unique companies from assigned users
            user_companies = set()
            for user in assigned_users:
                if user.company:
                    user_companies.add(user.company)
            
            if len(user_companies) == 1:
                # All users belong to same company, assign device to that company
                device.company = list(user_companies)[0]
            else:
                # Multiple companies or no company, default to REDPAY
                device.company = redpay_company
        else:
            # No assigned users, default to REDPAY
            device.company = redpay_company
        
        device.save(update_fields=['company'])
        devices_updated += 1
    print(f"Migrated {devices_updated} devices to companies")


def reverse_migration(apps, schema_editor):
    """Reverse migration - set company fields to None"""
    DashUser = apps.get_model('api', 'DashUser')
    Device = apps.get_model('api', 'Device')
    
    DashUser.objects.update(company=None)
    Device.objects.update(company=None)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_telegrambot_enhanced_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Company code (REDPAY, BROPAY, HYPAY, CSAPAY, KYPAY)', max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Company display name', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether company is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['code'],
            },
        ),
        migrations.RenameIndex(
            model_name='telegrambot',
            new_name='telegram_bo_name_193561_idx',
            old_name='telegram_bo_name_idx',
        ),
        migrations.RenameIndex(
            model_name='telegrambot',
            new_name='telegram_bo_is_acti_f007f3_idx',
            old_name='telegram_bo_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='telegrambot',
            new_name='telegram_bo_chat_ty_428e30_idx',
            old_name='telegram_bo_chat_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='telegrambot',
            new_name='telegram_bo_last_us_4a32bc_idx',
            old_name='telegram_bo_last_us_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_reset', 'Password Reset'), ('profile_update', 'Profile Update'), ('access_level_change', 'Access Level Change'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('device_assignment', 'Device Assignment'), ('device_unassignment', 'Device Unassignment')], db_index=True, help_text='Type of activity performed', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='access_level',
            field=models.IntegerField(choices=[(0, 'ADMIN'), (1, 'OTP'), (2, 'REDPAY')], db_index=True, default=1, help_text="Access level: 0 = ADMIN (can allocate to any company), 1 = OTP, 2 = COMPANY_USER (see only their company's devices)"),
        ),
        migrations.AlterField(
            model_name='device',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='[DEPRECATED] Dashboard users this device is assigned to. Use company field instead. Keeping for backward compatibility.', related_name='assigned_devices', to='api.dashuser'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['code'], name='api_company_code_cdd9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='api_company_is_acti_4e80aa_idx'),
        ),
        migrations.AddField(
            model_name='dashuser',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this user belongs to (REDPAY, BROPAY, HYPAY, CSAPAY, KYPAY)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.company'),
        ),
        migrations.AddField(
            model_name='device',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this device is allocated to (REDPAY, BROPAY, HYPAY, CSAPAY, KYPAY). All users in this company can see the device.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='api.company'),
        ),
        migrations.AddIndex(
            model_name='dashuser',
            index=models.Index(fields=['company'], name='api_dashuse_company_41610a_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company'], name='api_device_company_924b78_idx'),
        ),
        # Data migration: Create companies and migrate existing data
        migrations.RunPython(
            create_companies_and_migrate_data,
            reverse_migration,
        ),
    ]
