# Generated by Django 5.0.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_company_model_and_device_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(blank=True, db_index=True, default='', help_text='Telegram chat ID (set when user sends /link <token>)', max_length=64)),
                ('link_token', models.CharField(blank=True, db_index=True, help_text='One-time token for /link command (cleared after linking)', max_length=64, null=True)),
                ('link_token_expires_at', models.DateTimeField(blank=True, help_text='When the link token expires', null=True)),
                ('opted_in_alerts', models.BooleanField(default=True, help_text='Receive general alerts')),
                ('opted_in_reports', models.BooleanField(default=False, help_text='Receive reports')),
                ('opted_in_device_events', models.BooleanField(default=True, help_text='Receive device events (offline, battery, sync)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company this link belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='telegram_links', to='api.company')),
                ('telegram_bot', models.ForeignKey(help_text='Bot used for this link', on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='api.telegrambot')),
                ('user', models.ForeignKey(blank=True, help_text='Dashboard user who created the link (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_links', to='api.dashuser')),
            ],
            options={
                'verbose_name': 'Telegram User Link',
                'verbose_name_plural': 'Telegram User Links',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='telegramuserlink',
            index=models.Index(fields=['company', 'telegram_chat_id'], name='api_telegram_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='telegramuserlink',
            constraint=models.UniqueConstraint(condition=models.Q(telegram_chat_id__gt=''), fields=('company', 'telegram_chat_id'), name='unique_company_telegram_chat'),
        ),
    ]
